### PR TITLE
Added description to musician :musical_score: 

### PR DESCRIPTION
**Pull request by alexandrelam**
front pr: https://github.com/Find-A-Musician/findAMusicianFrontend/pull/77

### CODE REVIEW

**Comment by RomainGuarinoni** [comment]
Need tp update the OpenAPI defs, i will do it !

**Comment by alexandrelam** [comment]
> Need toupdate the OpenAPI defs, i will do it !

I was trying to find the file but couldn't manage to find it... Please do it for this pr. I'll do it next time.

**Comment by alexandrelam** [comment]
@RomainGuarinoni I updated open api. Is this enough? or did i forget smt?

**Comment by RomainGuarinoni** [comment]
I think it's good , i can't really check rn but merge it for the moment !

**Pull request merged**
